package net.magli143.exo;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : membuf.h:4</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class membuf extends Structure {
	/** C type : void* */
	public Pointer buf;
	public int len;
	public int size;
	public membuf() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("buf", "len", "size");
	}
	/** @param buf C type : void* */
	public membuf(Pointer buf, int len, int size) {
		super();
		this.buf = buf;
		this.len = len;
		this.size = size;
	}
	public static class ByReference extends membuf implements Structure.ByReference {
		
	};
	public static class ByValue extends membuf implements Structure.ByValue {
		
	};
}
